// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAPI.Connection;

namespace ProjectAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectAPI.Models.CAR", b =>
                {
                    b.Property<int>("CAR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CAR_CATEGORY_ID")
                        .HasColumnType("int");

                    b.Property<string>("CAR_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DELETED")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLATE_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PRICE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VERSION")
                        .HasColumnType("int");

                    b.HasKey("CAR_ID");

                    b.ToTable("CAR");
                });
#pragma warning restore 612, 618
        }
    }
}
